### ISSUE TITLE
APL was the main inspiration for the initial Numerical Python API

### ISSUE THREAD

**Issue by khinsen** [ThePoetCoder/APL-to-NumPy#2]
You may find interesting discussions in the still available [archive of the Matrix-SIG mailing list](https://mail.python.org/pipermail/matrix-sig/).

Some operations have very APL-like equivalents that are hardly used today (and maybe hardly known). Example from the notebook:

```
#       +/ 1 2 3
# 6

np.array([1, 2, 3]).sum()
```

A better NumPy equivalent  is
```
np.add.reduce([1, 2, 3])
```
And yes, `reduce` is available on all binary operators, which all have a function equivalent to make this possible.

**Comment by ThePoetCoder** [comment]
Indeed, this is much better, thank you for pointing that out! That cell has been changed [as of now](https://github.com/ThePoetCoder/APL-to-NumPy/commit/5340a9e69c8f39f4321729d04398ac55c34d8ff9).
