### ISSUE TITLE
Convert Jupyter Notebook to README

### ISSUE THREAD

**Issue by sohang3112** [ThePoetCoder/APL-to-NumPy#3]
[This example](https://andrewpwheeler.com/2021/09/06/using-jupyter-notebooks-to-make-nice-readmes-for-github/) shows how a README.md file can be automatically generated from a Jupyter Notebook.

**Comment by ThePoetCoder** [comment]
I've decided not to use this method for creating a Readme and instead just wrote my own the old fashioned way.

This issue is resolved as of now: https://github.com/ThePoetCoder/APL-to-NumPy/commit/df9bd7973c6941ef6c2a34b96497fe9820766c4b
